
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultListModel;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Windows 10 Version 2
 */
public class FontProperty extends javax.swing.JDialog {

    /**
     * Creates new form FontProperty
     */
    MTE h;
//    private final DefaultListModel DLM;

    public FontProperty(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        h = (MTE) parent;
//        DLM = new DefaultListModel();
//        listFont.setModel(DLM);
//        loadFontHelper();
//        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    }

//    public void loadFontHelper() {
////        Font font = new FontProperty(parent, rootPaneCheckingEnabled)
//        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
//        String[] fontFamilyNames = ge.getAvailableFontFamilyNames();
//        listFont.setListData(fontFamilyNames);
//        String[] sizes = {"8", "10", "12", "16", "18", "20", "24", "28", "32", "48", "72"};
//        lstSize.setListData(sizes);
//        String[] styles = {"Plain", "Bold", "Italic", "Bold Italic"};
//        lstStyle.setListData(styles);
//    }

//    public void setDefault(String name, int style, int size) {
//        listFont.setSelectedValue(name, true);
//        lstSize.setSelectedValue(5, true);
//        style = lstStyle.getSelectedIndex();
//        switch (style) {
//            case 0:
//                txtPreview.setFont(new Font(name, Font.PLAIN, size));
//                break;
//            case 1:
//                txtPreview.setFont(new Font(name, Font.BOLD, size));
//                break;
//            case 2:
//                txtPreview.setFont(new Font(name, Font.ITALIC, size));
//                break;
//            case 3:
//                txtPreview.setFont(new Font(name, Font.BOLD + Font.ITALIC, size));
//                break;
//            default:
//                break;
//        }
//        lstStyle.setSelectedIndex(style);
//    }

//    public void setSelectedFont(JTextArea txt) {
//        String name = listFont.getSelectedValue();
//        int style = lstStyle.getSelectedIndex();
//        int size = Integer.parseInt(lstSize.getSelectedValue());
//        switch (style) {
//            case 0:
//                txt.setFont(new Font(name, Font.PLAIN, size));
//                break;
//            case 1:
//                txt.setFont(new Font(name, Font.BOLD, size));
//                break;
//            case 2:
//                txt.setFont(new Font(name, Font.ITALIC, size));
//                break;
//            case 3:
//                txt.setFont(new Font(name, Font.BOLD + Font.ITALIC, size));
//                break;
//            default:
//                break;
//        }
//
//    }

    /**
     * This method is called from within the constructor to initial ize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listFont = new javax.swing.JList<>();
        btnChoose = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstStyle = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSize = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPreview = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 385));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listFontMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listFont);

        btnChoose.setText("OK");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Font:");

        lstStyle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstStyleMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(lstStyle);

        lstSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstSizeMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(lstSize);

        jLabel2.setText("Style:");

        jLabel3.setText("Size:");

        txtPreview.setEditable(false);
        txtPreview.setColumns(20);
        txtPreview.setRows(5);
        txtPreview.setText("AaBbCcDdEeFfGgHhIiJj");
        jScrollPane4.setViewportView(txtPreview);

        jLabel4.setText("Font preview:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(btnChoose)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChoose)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
//        setSelectedFont(h.txtA);
//        this.setVisible(false);
    }//GEN-LAST:event_btnChooseActionPerformed

    private void listFontMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFontMouseReleased
//        setSelectedFont(txtPreview);
    }//GEN-LAST:event_listFontMouseReleased

    private void lstSizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstSizeMouseReleased
//        setSelectedFont(txtPreview);
    }//GEN-LAST:event_lstSizeMouseReleased

    private void lstStyleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstStyleMouseReleased
//        setSelectedFont(txtPreview);
    }//GEN-LAST:event_lstStyleMouseReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
//        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        setDefault("Arial", 1, 5);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FontProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FontProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FontProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FontProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FontProperty dialog = new FontProperty(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listFont;
    private javax.swing.JList<String> lstSize;
    private javax.swing.JList<String> lstStyle;
    private javax.swing.JTextArea txtPreview;
    // End of variables declaration//GEN-END:variables
}
